# Generated by Django 4.2.1 on 2023-06-15 14:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(
                default='#FF0000',
                image_field=None,
                max_length=18,
                samples=None,
                unique=True,
                verbose_name='Цвет'),
        ),
    ]
