# Generated by Django 4.2.1 on 2023-06-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_favorite_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('color',), name='Цвет должен быть уникальным'),
        ),
    ]
