# Generated by Django 4.2.1 on 2023-06-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_tag_цвет_должен_быть_уникальным'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='Цвет должен быть уникальным',
        ),
    ]
