# Generated by Django 4.2.1 on 2023-06-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_subscribe_unique_user_subscribe_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('user',
                     models.F('following')),
                    _negated=True),
                name='Нельзя подписываться на себя'),
        ),
    ]
